### ISSUE TITLE
install with pip on windows failing

### ISSUE THREAD

**Issue by MikeTheWatchGuy** [cslarsen/arv#2]
This is my first ever issue posted on Github.  I hope I'm not wasting someone's time.  I saw one contributor's comment that any problems users run into should get logged as an issue, so, I'm following suggestions :-)
Regardless, I'm sorry if I misread something or am making a rookie error.

I'm trying to install using pip and am getting same failure with 2 different Python 3 setups.  One is Anaconda3 the other Python34.

I invoked this command that has worked with other package installations:
Python -m pip install arv

This is a dump from that session:
C:\Python34>python -m pip install arv
Collecting arv
  Using cached arv-0.9.2.tar.gz
    Complete output from command python setup.py egg_info:
    Compiling C:\Users\mike\AppData\Local\Temp\easy_install-ilunbc5p\Cython-0.27.1\Cython\Plex\Scanners.py because it changed.
    Compiling C:\Users\mike\AppData\Local\Temp\easy_install-ilunbc5p\Cython-0.27.1\Cython\Plex\Actions.py because it changed.
    Compiling C:\Users\mike\AppData\Local\Temp\easy_install-ilunbc5p\Cython-0.27.1\Cython\Compiler\Pythran.py because it changed.
    Compiling C:\Users\mike\AppData\Local\Temp\easy_install-ilunbc5p\Cython-0.27.1\Cython\Compiler\Lexicon.py because it changed.
    Compiling C:\Users\mike\AppData\Local\Temp\easy_install-ilunbc5p\Cython-0.27.1\Cython\Compiler\Scanning.py because it changed.
    Compiling C:\Users\mike\AppData\Local\Temp\easy_install-ilunbc5p\Cython-0.27.1\Cython\Compiler\Parsing.py because it changed.
    Compiling C:\Users\mike\AppData\Local\Temp\easy_install-ilunbc5p\Cython-0.27.1\Cython\Compiler\Visitor.py because it changed.
    Compiling C:\Users\mike\AppData\Local\Temp\easy_install-ilunbc5p\Cython-0.27.1\Cython\Compiler\FlowControl.py because it changed.
    Compiling C:\Users\mike\AppData\Local\Temp\easy_install-ilunbc5p\Cython-0.27.1\Cython\Compiler\Code.py because it changed.
    Compiling C:\Users\mike\AppData\Local\Temp\easy_install-ilunbc5p\Cython-0.27.1\Cython\Runtime\refnanny.pyx because it changed.
    Compiling C:\Users\mike\AppData\Local\Temp\easy_install-ilunbc5p\Cython-0.27.1\Cython\Tempita\_tempita.py because it changed.
    [ 1/11] Cythonizing C:\Users\mike\AppData\Local\Temp\easy_install-ilunbc5p\Cython-0.27.1\Cython\Compiler\Code.py
    [ 2/11] Cythonizing C:\Users\mike\AppData\Local\Temp\easy_install-ilunbc5p\Cython-0.27.1\Cython\Compiler\FlowControl.py
    [ 3/11] Cythonizing C:\Users\mike\AppData\Local\Temp\easy_install-ilunbc5p\Cython-0.27.1\Cython\Compiler\Lexicon.py
    [ 4/11] Cythonizing C:\Users\mike\AppData\Local\Temp\easy_install-ilunbc5p\Cython-0.27.1\Cython\Compiler\Parsing.py
    [ 5/11] Cythonizing C:\Users\mike\AppData\Local\Temp\easy_install-ilunbc5p\Cython-0.27.1\Cython\Compiler\Pythran.py
    [ 6/11] Cythonizing C:\Users\mike\AppData\Local\Temp\easy_install-ilunbc5p\Cython-0.27.1\Cython\Compiler\Scanning.py
    [ 7/11] Cythonizing C:\Users\mike\AppData\Local\Temp\easy_install-ilunbc5p\Cython-0.27.1\Cython\Compiler\Visitor.py
    [ 8/11] Cythonizing C:\Users\mike\AppData\Local\Temp\easy_install-ilunbc5p\Cython-0.27.1\Cython\Plex\Actions.py
    [ 9/11] Cythonizing C:\Users\mike\AppData\Local\Temp\easy_install-ilunbc5p\Cython-0.27.1\Cython\Plex\Scanners.py
    [10/11] Cythonizing C:\Users\mike\AppData\Local\Temp\easy_install-ilunbc5p\Cython-0.27.1\Cython\Runtime\refnanny.pyx
    [11/11] Cythonizing C:\Users\mike\AppData\Local\Temp\easy_install-ilunbc5p\Cython-0.27.1\Cython\Tempita\_tempita.py
    Unable to find pgen, not compiling formal grammar.
    warning: no files found matching '2to3-fixers.txt'
    warning: no files found matching 'Doc\*'
    warning: no files found matching '*.pyx' under directory 'Cython\Debugger\Tests'
    warning: no files found matching '*.pxd' under directory 'Cython\Debugger\Tests'
    warning: no files found matching '*.pxd' under directory 'Cython\Utility'
    Traceback (most recent call last):
      File "C:\Python34\lib\site-packages\setuptools\msvc9_support.py", line 52, in query_vcvarsall
        return unpatched['query_vcvarsall'](version, *args, **kwargs)
      File "C:\Python34\lib\distutils\msvc9compiler.py", line 259, in query_vcvarsall
        raise DistutilsPlatformError("Unable to find vcvarsall.bat")
    distutils.errors.DistutilsPlatformError: Unable to find vcvarsall.bat

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Python34\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "C:\Python34\lib\distutils\dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "C:\Python34\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "C:\Python34\lib\site-packages\setuptools\command\bdist_egg.py", line 160, in run
        cmd = self.call_command('install_lib', warn_dir=0)
      File "C:\Python34\lib\site-packages\setuptools\command\bdist_egg.py", line 146, in call_command
        self.run_command(cmdname)
      File "C:\Python34\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\Python34\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "C:\Python34\lib\site-packages\setuptools\command\install_lib.py", line 10, in run
        self.build()
      File "C:\Python34\lib\distutils\command\install_lib.py", line 107, in build
        self.run_command('build_ext')
      File "C:\Python34\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\Python34\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "C:\Python34\lib\site-packages\setuptools\command\build_ext.py", line 49, in run
        _build_ext.run(self)
      File "C:\Python34\lib\distutils\command\build_ext.py", line 339, in run
        self.build_extensions()
      File "C:\Python34\lib\distutils\command\build_ext.py", line 448, in build_extensions
        self.build_extension(ext)
      File "C:\Python34\lib\site-packages\setuptools\command\build_ext.py", line 174, in build_extension
        _build_ext.build_extension(self, ext)
      File "C:\Python34\lib\distutils\command\build_ext.py", line 503, in build_extension
        depends=ext.depends)
      File "C:\Python34\lib\distutils\msvc9compiler.py", line 460, in compile
        self.initialize()
      File "C:\Python34\lib\distutils\msvc9compiler.py", line 371, in initialize
        vc_env = query_vcvarsall(VERSION, plat_spec)
      File "C:\Python34\lib\site-packages\setuptools\msvc9_support.py", line 62, in query_vcvarsall
        raise distutils.errors.DistutilsPlatformError(message)
    distutils.errors.DistutilsPlatformError: Microsoft Visual C++ 10.0 is required (Unable to find vcvarsall.bat).

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Python34\lib\site-packages\setuptools\sandbox.py", line 152, in save_modules
        yield saved
      File "C:\Python34\lib\site-packages\setuptools\sandbox.py", line 193, in setup_context
        yield
      File "C:\Python34\lib\site-packages\setuptools\sandbox.py", line 237, in run_setup
        DirectorySandbox(setup_dir).run(runner)
      File "C:\Python34\lib\site-packages\setuptools\sandbox.py", line 267, in run
        return func()
      File "C:\Python34\lib\site-packages\setuptools\sandbox.py", line 236, in runner
        _execfile(setup_script, ns)
      File "C:\Python34\lib\site-packages\setuptools\sandbox.py", line 46, in _execfile
        exec(code, globals, locals)
      File "C:\Users\mike\AppData\Local\Temp\easy_install-ilunbc5p\Cython-0.27.1\setup.py", line 278, in <module>
      File "C:\Python34\lib\distutils\core.py", line 163, in setup
        raise SystemExit("error: " + str(msg))
    SystemExit: error: Microsoft Visual C++ 10.0 is required (Unable to find vcvarsall.bat).

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Python34\lib\site-packages\setuptools\command\easy_install.py", line 1056, in run_setup
        run_setup(setup_script, args)
      File "C:\Python34\lib\site-packages\setuptools\sandbox.py", line 240, in run_setup
        raise
      File "C:\Python34\lib\contextlib.py", line 77, in __exit__
        self.gen.throw(type, value, traceback)
      File "C:\Python34\lib\site-packages\setuptools\sandbox.py", line 193, in setup_context
        yield
      File "C:\Python34\lib\contextlib.py", line 77, in __exit__
        self.gen.throw(type, value, traceback)
      File "C:\Python34\lib\site-packages\setuptools\sandbox.py", line 164, in save_modules
        saved_exc.resume()
      File "C:\Python34\lib\site-packages\setuptools\sandbox.py", line 139, in resume
        compat.reraise(type, exc, self._tb)
      File "C:\Python34\lib\site-packages\setuptools\compat.py", line 65, in reraise
        raise value.with_traceback(tb)
      File "C:\Python34\lib\site-packages\setuptools\sandbox.py", line 152, in save_modules
        yield saved
      File "C:\Python34\lib\site-packages\setuptools\sandbox.py", line 193, in setup_context
        yield
      File "C:\Python34\lib\site-packages\setuptools\sandbox.py", line 237, in run_setup
        DirectorySandbox(setup_dir).run(runner)
      File "C:\Python34\lib\site-packages\setuptools\sandbox.py", line 267, in run
        return func()
      File "C:\Python34\lib\site-packages\setuptools\sandbox.py", line 236, in runner
        _execfile(setup_script, ns)
      File "C:\Python34\lib\site-packages\setuptools\sandbox.py", line 46, in _execfile
        exec(code, globals, locals)
      File "C:\Users\mike\AppData\Local\Temp\easy_install-ilunbc5p\Cython-0.27.1\setup.py", line 278, in <module>
      File "C:\Python34\lib\distutils\core.py", line 163, in setup
        raise SystemExit("error: " + str(msg))
    SystemExit: error: Microsoft Visual C++ 10.0 is required (Unable to find vcvarsall.bat).

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\mike\AppData\Local\Temp\pip-build-s90q0wka\arv\setup.py", line 165, in <module>
        "Programming Language :: Python :: 3.6",
      File "C:\Python34\lib\distutils\core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "C:\Python34\lib\site-packages\setuptools\dist.py", line 268, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "C:\Python34\lib\site-packages\setuptools\dist.py", line 313, in fetch_build_eggs
        replace_conflicting=True,
      File "C:\Python34\lib\site-packages\pkg_resources\__init__.py", line 836, in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "C:\Python34\lib\site-packages\pkg_resources\__init__.py", line 1081, in best_match
        return self.obtain(req, installer)
      File "C:\Python34\lib\site-packages\pkg_resources\__init__.py", line 1093, in obtain
        return installer(requirement)
      File "C:\Python34\lib\site-packages\setuptools\dist.py", line 380, in fetch_build_egg
        return cmd.easy_install(req)
      File "C:\Python34\lib\site-packages\setuptools\command\easy_install.py", line 629, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "C:\Python34\lib\site-packages\setuptools\command\easy_install.py", line 659, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "C:\Python34\lib\site-packages\setuptools\command\easy_install.py", line 842, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "C:\Python34\lib\site-packages\setuptools\command\easy_install.py", line 1070, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "C:\Python34\lib\site-packages\setuptools\command\easy_install.py", line 1058, in run_setup
        raise DistutilsError("Setup script exited with %s" % (v.args[0],))
    distutils.errors.DistutilsError: Setup script exited with error: Microsoft Visual C++ 10.0 is required (Unable to find vcvarsall.bat).

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\mike\AppData\Local\Temp\pip-build-s90q0wka\arv\

C:\Python34>

**Comment by cslarsen** [comment]
Hi, you need a compiler on Windows. It seems it's looking for Visual Studio 10.0. Do you have it? There should be a file vcvars.bat along with it that sets up all environment variables needed to compile on the command line.

**Comment by MikeTheWatchGuy** [comment]
Dang... I see.  It wants to compile some C code?
Is there a list of dependencies for this library so that I can make sure I get all the stuff I need?

I do not currently have Visual Studio installed.  It's been a while since I've written C code as I tend to use a program call WinAutomation to do pretty much all of my Windows utility tasks.  BUT, I think I can likely replace it with Python.  Python is new to me (but have been coding since late 70s). 

Thanks for the reply!

**Comment by cslarsen** [comment]
The only requirement is a C++11 compiler, and you need to install it via pip. It will take care of installing everything needed in addition (Cython, etc.)

**Comment by MikeTheWatchGuy** [comment]
Very good... thank you!  I'm off on another project at the moment. Will turn back to this soon.  I really appreciate the help
