### ISSUE TITLE
error during installation (Google hash map)

### ISSUE THREAD

**Issue by mrx23dot** [cslarsen/arv#5]
On Win10 x64, Python 3.6.3 I get an error during installation (  RuntimeError: Error configuring Google hash map)

pipenv install arv
Installing arv…
Looking in indexes: https://pypi.python.org/simple
Collecting arv
  Downloading https://files.pythonhosted.org/packages/c2/6a/7198d7adcb9e5f90080c5f2e0bd9dced045f174dd809267b626278995b67/arv-0.9.2.tar.gz (264kB)
Collecting cython>=0.25
  Using cached https://files.pythonhosted.org/packages/94/44/6e5aee9916a53f56d32da0770962c9571f8267cd2327b9e58db656d61efe/Cython-0.29.14-cp36-cp36m-win32.whl
Building wheels for collected packages: arv
  Building wheel for arv (setup.py): started
  Building wheel for arv (setup.py): finished with status 'error'
  Running setup.py clean for arv
Failed to build arv
Installing collected packages: cython, arv
    Running setup.py install for arv: started
    Running setup.py install for arv: finished with status 'error'
Error:  An error occurred while installing arv!
  ERROR: Command errored out with exit status 1:
   command: 'c:\users\jack\.virtualenvs\test2-dj1oiwoc\scripts\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\jack\\AppData\\Local\\Temp\\pip-install-rj7yah2s\\arv\\setup.py'"'"'; __file__='"'"'C:\\Users\\jack\\AppData\\Local\\Temp\\pip-install-rj7yah2s\\arv\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\jack\AppData\Local\Temp\pip-wheel-rpv4lk08' --python-tag cp36
       cwd: C:\Users\jack\AppData\Local\Temp\pip-install-rj7yah2s\arv\
  Complete output (46 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win32-3.6
  creating build\lib.win32-3.6\arv
  copying arv\match.py -> build\lib.win32-3.6\arv
  copying arv\traits.py -> build\lib.win32-3.6\arv
  copying arv\util.py -> build\lib.win32-3.6\arv
  copying arv\__init__.py -> build\lib.win32-3.6\arv
  copying arv\__main__.py -> build\lib.win32-3.6\arv
  warning: build_py: byte-compiling is disabled, skipping.
  running build_ext
  Configuring Google hash map
  '3rd-party\sparsehash\configure' is not recognized as an internal or external command,
  operable program or batch file.
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\jack\AppData\Local\Temp\pip-install-rj7yah2s\arv\setup.py", line 165, in <module>
      "Programming Language :: Python :: 3.6",
    File "c:\users\jack\.virtualenvs\test2-dj1oiwoc\lib\site-packages\setuptools\__init__.py", line 145, in setup
      return distutils.core.setup(**attrs)
    File "c:\python36-32\Lib\distutils\core.py", line 148, in setup
      dist.run_commands()
    File "c:\python36-32\Lib\distutils\dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "c:\python36-32\Lib\distutils\dist.py", line 974, in run_command
      cmd_obj.run()
    File "c:\users\jack\.virtualenvs\test2-dj1oiwoc\lib\site-packages\wheel\bdist_wheel.py", line 192, in run
      self.run_command('build')
    File "c:\python36-32\Lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "c:\python36-32\Lib\distutils\dist.py", line 974, in run_command
      cmd_obj.run()
    File "c:\python36-32\Lib\distutils\command\build.py", line 135, in run
      self.run_command(cmd_name)
    File "c:\python36-32\Lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "c:\python36-32\Lib\distutils\dist.py", line 974, in run_command
      cmd_obj.run()
    File "C:\Users\jack\AppData\Local\Temp\pip-install-rj7yah2s\arv\setup.py", line 86, in run
      configure_google_hashmap()
    File "C:\Users\jack\AppData\Local\Temp\pip-install-rj7yah2s\arv\setup.py", line 82, in configure_google_hashmap
      raise RuntimeError("Error configuring Google hash map")
  **RuntimeError: Error configuring Google hash map**

**Comment by duaneking** [comment]
Getting the same issue.  I really hope this isnt broken by google.

**Comment by duaneking** [comment]
You have a broken install because the google stuff no longer works or possibly never worked on windows, and its failing to install.

Edit: Just Use WSL and use a virtualenv.
